### ISSUE TITLE
Server limited

### ISSUE THREAD

**Issue by Xydote** [shikhir-arora/karma-simple#9]
How to modify it so that it becomes server limited and not global?

**Comment by shikhir-arora** [comment]
Sorry for the delay in getting back to you. I somehow missed this issue. Are you planning to self-host the bot yourself? 

I'm not sure I understand your question. Are you asking if the public KarmaBot can be server-limited with regards to Karma being per-server? If that's the question, at this time I have no plans on doing that for two reasons:

- Karma is meant to be cross-guild and the schema and database are setup like this

- I can't introduce such a change without refactoring the concept of the bot, and this was a simple IRC-inspired bot that's properly coded with modern ES8 as a guideline for others or just something to use to keep track of any keyword. Unfortunately changing it to a server-only thing would break the premise that 1,000+ servers use it on.

If you do plan to self-host the bot yourself, with your own bot account, then it's doable. If you self host it in one server it inherently is server limited, but if you needed it to be server limited I could do it depending on some things (are you willing to learn? 😀). I don't make bots for people but I'll happily guide you through the process of it if you're self hosting. If this is the case, contact me on Discord at `.vlexar#0001` or join my guild and mention this. https://invite.gg/ec to join.

**Comment by shikhir-arora** [comment]
Going to close this since I haven't heard back. Feel free to reopen or reach out if you do have any further questions.
